### ISSUE TITLE
Add signing capabilities

### ISSUE THREAD

**Issue by amyramos** [pkosilo/gorm-crypto#8]
**Is your feature request related to a problem? Please describe.**
Maybe it will be a great feature to have an opportunity to add signatures to data stored in the database. So, it will be possible to verify integrity of data stored in the database on the client side. It can be used to determine if there were changes of the signed data.

**Describe the solution you'd like**
Add a new structure called `SignedValue` which will use `SignatureAlgorithms` variable and as `EncryptedValue` use the first algorithm to sign data and use other algorithms with lower priority (fallbacks) if it's not possible to verify signature with the first (primary) algorithm. Example `SignedValue` struct based on `EncryptedValue`:
```golang
type SignedValue struct {
    Raw   interface{} `json:"Raw"`
    Valid bool        `json:"Valid"`
}
```
`Raw` is value which is stored in the database, `Valid` is boolean which tells if the `Raw` value is signed correctly.

**Comment by amyramos** [comment]
@pkosilo, I'd like to work on it myself

**Comment by pkosilo** [comment]
> @pkosilo, I'd like to work on it myself

Okay 👍
